In [1]:
import pandas as pd
import numpy as np

In [2]:
#warnings
import warnings
warnings.filterwarnings('ignore')

In [6]:
import os
os.chdir(r"C:\Users\tfarotimi\OneDrive - United Nations\Documents\CEPAL\Tasa-Natural-de-Interes\HLW_2023_Replication_Code\HLW_2023_Replication_Code")

In [7]:
# Read input data from FRBNY website
mex_gdp =  pd.read_excel("inputData/mex_data.xlsx", sheet_name="GDP")
mex_gdp = mex_gdp.set_index("Date")
mex_gdp['gdp.log'] = np.log(mex_gdp['gdp.raw'])
#drop gdp raw
mex_gdp = mex_gdp.drop(columns = ['gdp.raw'])
mex_gdp

              gdp.log
Date
1993-01-01  16.124658
1993-04-01  16.127315
1993-07-01  16.137493
1993-10-01  16.150647
1994-01-01  16.160783
...               ...
2022-01-01  16.711318
2022-04-01  16.722300
2022-07-01  16.731408
2022-10-01  16.737177
2023-01-01  16.747332

[121 rows x 1 columns]

In [8]:
mex_inflation =  pd.read_excel("inputData/mex_data.xlsx", sheet_name="Inflation")
mex_inflation = mex_inflation.set_index("Date")
mex_inflation['index'] = np.nan
#create index from monthly increase
#set first row to 100
mex_inflation['index'].iloc[0] = 100
mex_inflation
for i in range(1,len(mex_inflation)):
    mex_inflation['index'][i] = ((mex_inflation['inflation.mensual'][i]/100) * mex_inflation['index'][i-1]) + mex_inflation['index'][i-1]

#resample 'index'column to quarterly
mex_inflation = mex_inflation['index'].resample('QS').mean()
mex_inflation['growth'] = mex_inflation.pct_change() * 100
mex_inflation['growth'] = mex_inflation['growth'].dropna()

#annualize quarterly growth
mex_inflation['annualized'] =  100 * ((1 + mex_inflation['growth']/100)**4 - 1)
mex_inflation['annualized']
mex_inflation_final = mex_inflation['annualized'].to_frame()
mex_inflation_final['expectations'] = mex_inflation_final.rolling(4).mean()
mex_inflation_final

                 index  expectations
Date
1982-04-01   71.596407           NaN
1982-07-01  107.617491           NaN
1982-10-01  109.303424           NaN
1983-01-01  155.936492    111.113454
1983-04-01   81.410336    113.566936
...                ...           ...
2024-01-01    5.131156      4.639530
2024-04-01    3.463854      4.223897
2024-07-01    3.096590      3.982986
2024-10-01    3.013598      3.676299
2025-01-01    4.099206      3.418312

[172 rows x 2 columns]

In [9]:
#.interest
mex_interest =  pd.read_excel("inputData/mex_data.xlsx", sheet_name="Interest")
mex_interest = mex_interest.set_index("Date")
mex_interest = mex_interest.resample('QS').mean()
mex_interest['interest'] = mex_interest['interest'].dropna()
mex_interest

             interest
Date
2006-01-01   7.803333
2006-04-01   7.076667
2006-07-01   7.036667
2006-10-01   7.043333
2007-01-01   7.030000
...               ...
2024-04-01  11.006667
2024-07-01  10.860000
2024-10-01  10.393333
2025-01-01   9.673333
2025-04-01   9.010000

[78 rows x 1 columns]

In [10]:
#merge mex_gdp, mex_inflation_final, mex_interest
mex_data = pd.concat([mex_gdp, mex_inflation_final, mex_interest], axis=1).dropna()
mex_data
#change date format to YYYY-Q_1

mex_data.index = mex_data.index.to_period('Q')
mex_data

          gdp.log     index  expectations   interest
Date
2006Q1  16.481314  3.371753      3.120358   7.803333
2006Q2  16.491020  3.699673      3.316004   7.076667
2006Q3  16.493767  3.261528      3.435945   7.036667
2006Q4  16.496260  3.906739      3.559924   7.043333
2007Q1  16.503293  4.753614      3.905389   7.030000
...           ...       ...           ...        ...
2022Q1  16.711318  8.402055      6.550626   5.800000
2022Q2  16.722300  9.003384      7.361280   6.813333
2022Q3  16.731408  8.674146      8.012917   8.166667
2022Q4  16.737177  7.694987      8.443643   9.760000
2023Q1  16.747332  7.755858      8.282093  10.793333

[69 rows x 4 columns]

In [11]:
stringency = pd.read_csv("inputData/stringency.csv")
stringency_data = stringency[['CountryCode', 'Date', 'StringencyIndex_Average']]
stringency_data = stringency_data[stringency_data['CountryCode'] == 'MEX']
stringency_data = stringency_data.drop(columns=['CountryCode'])
# stringency_data['Date'] = pd.to_datetime(stringency_data['Date'])
stringency_data = stringency_data.set_index('Date')
#process 20200101 to 2020-01-01
stringency_data.index = pd.to_datetime(stringency_data.index, format='%Y%m%d')
stringency_data = stringency_data.resample('QS').mean()
stringency_data = stringency_data.rename(columns={'StringencyIndex_Average': 'covid.indicator'})
stringency_data.index = stringency_data.index.to_period('Q')
#add rows up to 2024Q1 with stringency declining linearly to 0
stringency_data = stringency_data.reindex(pd.period_range(start='2020Q1', end='2024Q1', freq='Q', name='Date'))
stringency_data.loc['2024Q1'] = 0
stringency_data = stringency_data.interpolate(method='linear')
#add rows forom 1990Q1 to 2019Q4 with stringency = 0
stringency_data = stringency_data.reindex(pd.period_range(start='1990Q1', end='2024Q1', freq='Q', name='Date'))
stringency_data = stringency_data.fillna(0)
stringency_data = stringency_data.dropna()
stringency_data

        covid.indicator
Date
1990Q1            0.000
1990Q2            0.000
1990Q3            0.000
1990Q4            0.000
1991Q1            0.000
...                 ...
2023Q1           11.112
2023Q2            8.334
2023Q3            5.556
2023Q4            2.778
2024Q1            0.000

[137 rows x 1 columns]

In [12]:
mex_data = mex_data.merge(stringency_data, left_index=True, right_on='Date')
mex_data

          gdp.log     index  expectations   interest  covid.indicator
Date
2006Q1  16.481314  3.371753      3.120358   7.803333         0.000000
2006Q2  16.491020  3.699673      3.316004   7.076667         0.000000
2006Q3  16.493767  3.261528      3.435945   7.036667         0.000000
2006Q4  16.496260  3.906739      3.559924   7.043333         0.000000
2007Q1  16.503293  4.753614      3.905389   7.030000         0.000000
...           ...       ...           ...        ...              ...
2022Q1  16.711318  8.402055      6.550626   5.800000        37.889778
2022Q2  16.722300  9.003384      7.361280   6.813333        24.866484
2022Q3  16.731408  8.674146      8.012917   8.166667        25.310217
2022Q4  16.737177  7.694987      8.443643   9.760000        13.890000
2023Q1  16.747332  7.755858      8.282093  10.793333        11.112000

[69 rows x 5 columns]

In [13]:
#rename columns
mex_data.columns = ['gdp.log', 'inflation', 'inflation.expectations', 'interest', 'covid.indicator']

#add columns of 0 called covid.indicator
#mex_data['covid.indicator'] = 0

#save data to excel
mex_data.to_excel("inputData/Holston_Laubach_Williams_MEX.xlsx", sheet_name="MEX Input Data" )